// solidjs/src/App.jsx
import { render } from "solid-js/web";
import Counter from './Counter'
import "./index.scss";

const App = () => (
  <div class="mt-10 text-3xl mx-auto max-w-6xl">
    <Counter />
    <div>Name: remote</div>
    <div>Framework: solid-js</div>
    <div>Language: JavaScript</div>
    <div>CSS: Tailwind</div>
  </div>
);
render(App, document.getElementById("app"));

// remote/src/App.jsx
import React from "react";
import ReactDOM from "react-dom";
import HeaderElement from "./HeaderElement";

import "./index.css";

const App = () => (
  <div className="container">
    <HeaderElement />
    <div>Name: remote</div>
    <div>Framework: react</div>
    <div>Language: JavaScript</div>
    <div>CSS: Empty CSS</div>
  </div>
);
ReactDOM.render(<App />, document.getElementById("remote-application"));
